swagger: '2.0'
info:
  title: Furniture Rental API
  version: 1.0.0
  description: API для аренды мебели
paths:
  /api/products:
    get:
      summary: Получить список товаров
      responses:
        '200':
          description: OK
  /api/orders:
    get:
      summary: Получить список заказов
      responses:
        '200':
          description: OK